{
 "title": "PoC-Dashboard",
 "description": "Monitoring of the PoC",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ping testen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ping test sample web app (ago 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "availabilityResults\r\n| where timestamp > ago(24h)\r\n| where name == \"Check-sample-app\"\r\n| summarize total = count(), failed = countif(success == false)\r\n| extend uptime = 100 - ((todouble(failed) / todouble(total)) * 100)\r\n\r\n",
      "resources": [
       "/subscriptions/6c516f03-07d2-44c8-8ab5-15d92d64f2f5/resourceGroups/PoC/providers/microsoft.insights/components/sample-webapp-idunnocorp-new"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Ping test did.json (ago 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "availabilityResults\r\n| where timestamp > ago(24h)\r\n| where name == \"Check-did-json\"\r\n| summarize total = count(), failed = countif(success == false)\r\n| extend uptime = 100 - ((todouble(failed) / todouble(total)) * 100)\r\n\r\n",
      "resources": [
       "/subscriptions/6c516f03-07d2-44c8-8ab5-15d92d64f2f5/resourceGroups/PoC/providers/microsoft.insights/components/sample-webapp-idunnocorp-new"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Ping test did-configuration.json (ago 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "availabilityResults\r\n| where timestamp > ago(24h)\r\n| where name == \"Check-did-configuration-json\"\r\n| summarize total = count(), failed = countif(success == false)\r\n| extend uptime = 100 - ((todouble(failed) / todouble(total)) * 100)\r\n\r\n",
      "resources": [
       "/subscriptions/6c516f03-07d2-44c8-8ab5-15d92d64f2f5/resourceGroups/PoC/providers/microsoft.insights/components/sample-webapp-idunnocorp-new"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  { "title": "Storage Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg Availability for idunnocorpstorage2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.storage/storageaccounts",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.Storage/storageAccounts",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "idunnocorpstorage2",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Sum Transactions for idunnocorpstorage2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.storage/storageaccounts",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.Storage/storageAccounts",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "idunnocorpstorage2",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Avg Success Server Latency for idunnocorpstorage2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.storage/storageaccounts",
      "metricName": "SuccessServerLatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.Storage/storageAccounts",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "idunnocorpstorage2",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Avg Success E2E Latency for idunnocorpstorage2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.storage/storageaccounts",
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.Storage/storageAccounts",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "idunnocorpstorage2",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Webapp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Count Failed request sample-webapp-idunnocorp-new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "westeurope",
        "resourceGroup": "PoC",
        "resourceName": "sample-webapp-idunnocorp-new",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
    }
   ]
  },
  {
   "title": "Sum Http Server Errors for sample-webapp-idunnocorp-new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.web/sites",
      "metricName": "Http5xx",
      "metricNamespace": "Microsoft.Web/sites",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "sample-webapp-idunnocorp-new",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Sum Requests for sample-webapp-idunnocorp-new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.web/sites",
      "metricName": "Requests",
      "metricNamespace": "Microsoft.Web/sites",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "sample-webapp-idunnocorp-new",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Sum Data Out for sample-webapp-idunnocorp-new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.web/sites",
      "metricName": "BytesSent",
      "metricNamespace": "Microsoft.Web/sites",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "sample-webapp-idunnocorp-new",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Sum Data In for sample-webapp-idunnocorp-new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.web/sites",
      "metricName": "BytesReceived",
      "metricNamespace": "Microsoft.Web/sites",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "sample-webapp-idunnocorp-new",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Key Vault", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Avg Overall Vault Availability for PoC-vault-new",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.keyvault/vaults",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.KeyVault/vaults",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "PoC-vault-new",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Avg Overall Service Api Latency for PoC-vault-new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.keyvault/vaults",
      "metricName": "ServiceApiLatency",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.KeyVault/vaults",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "PoC-vault-new",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Count Total Service Api Hits for PoC-vault-new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{ metric }} - {{ resourcename }}",
      "customNamespace": "microsoft.keyvault/vaults",
      "metricName": "ServiceApiHit",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "region": "",
      "resources": [
       {
        "metricNamespace": "Microsoft.KeyVault/vaults",
        "region": "",
        "resourceGroup": "PoC",
        "resourceName": "PoC-vault-new",
        "subscription": "6c516f03-07d2-44c8-8ab5-15d92d64f2f5"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}